services:
  - type: web
    name: pourevents-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Authentication__ApiKey
        generateValue: true
      - key: PORT
        value: "10000"
    healthCheckPath: /health
